#! /usr/bin/env python3
#  -*- coding:utf-8 -*-

import smbus
import time
import math

class HMC5883L:
	def __init__(self):
		self._bus = smbus.SMBus(1)
		self._sensor = 0x1E
		self._regs = {
			'CONF_A' : 0x00,
			'CONF_B' : 0x01,
			'MODE' 	 : 0x02,
			'X' 	 : 0x03,
			'Y' 	 : 0x07,
			'Z' 	 : 0x05,
			'STATUS' : 0x09,
		}
		self._tblVersterking = {
			0.88: [0x00, 0.73],
			1.3 : [0x20, 0.92],
			1.9 : [0x40, 1.22],
			2.5 : [0x60, 1.52],
			4.0 : [0x80, 2.27],
			4.7 : [0xA0, 2.56],
			5.6 : [0xC0, 3.03],
			8.1 : [0xE0, 4.35]			
		}
		
		#REGISTER CONF_A
		#gemiddelde aantal metingen
		#bit 6 + 5
		#0x00 1 met, 0x20 2 met, 0x40 4 met, 0x60 8 met
		self._regA_gem = 0x60
		
		#overdracht shelheid
		#bit 4 + 3 + 2
		#0x00 0.75Hz, 0x40 1.5Hz, 0x80 3Hz, 0xC0 7.5Hz
		#0x00 15Hz standaard, 0x14 30 Hz, 0x18 75 Hz
		self._regA_overdracht = 0x10
		
		#meetmode
		# bit 1 + 0
		#0x00 standaard, 0x01 positieve bias
		# 0x02 negatieve bias, 0x03 gereserveerd
		self._regA_meetmode = 0x00
		
		#register B
		# verstreking
		self._verstreking = 1.3
		self._regB_verstreking = self._tblVersterking[self._verstreking][0]
		self._regB_schaal = self._tblVersterking[self._verstreking][1]
		
		#meetmode
		# bit 1 + 0
		# 0x00 continu meten, 0x01 enkelvoudig meten
		self._regMode_mode = 0x01		
	
	def zetGemMeting(self, aantal=8):
		pass
	
	def zetEnkelvoudigMeten(self, aantal=8):
		pass
	
	def zetContinuMeet(self):
		pass
	
	def zetVerstreking(self, verstreking=1.3):
		pass
	
	def zetOverdracht(self, snelheid=1):
		pass
	
	def meet(self):
		regA = self._regA_gem + self._regA_overdracht + self._regA_meetmode		 
		
		print(hex(self._sensor))
		print(hex(self._regs['CONF_A']))
		print(hex(regA))
		
		self._bus.write_byte_data(0x1e, 0x00, 0x71)
		
		regB = self._regB_verstreking
		self._bus.write_byte_data(self._sensor, self._regs['CONF_B'], regB)
		
		regMode = self._regMode_mode
		self._bus.write_byte_data(self._sensor, self._regs['MODE'], regMode)
		
		return self._verwerk()
		
		
	def zelftest(self): 		
		print('=========== Start writing ===========')
		print(self._sensor)
		print(self._regs['CONF_A'])
		print('0x71')
		self._bus.write_byte_data(self._sensor, self._regs['CONF_A'], 0x71)
		self._bus.write_byte_data(self._sensor, self._regs['CONF_B'], 0xA0)		
		self._bus.write_byte_data(self._sensor, self._regs['MODE'], 0x00)	
		return _verwerk()	 
		
	def _tweeComplement(self, getal=0):
		if(getal > 0x8000):	
			getal = -((65535 - getal) + 1)
		return getal
					
	def _verwerk(self):
		time.sleep(0.007)
		while self._bus.read_byte_data(self._sensor, self._regs['STATUS']) & 0x01 == 0x00:
			time.sleep(0.00025)
			
		xmsb, xlsb, zmsb, zlsb, ymsb, ylsb = self._bus.read_i2c_block_data(self._sensor, self._regs['X'], 6)
		
		x = self._tweeComplement(256 * xmsb + xlsb)
		x *= self._regB_schaal
		
		y = self._tweeComplement(256 * ymsb + ylsb)
		y *= self._regB_schaal
		
		z = self._tweeComplement(256 * zmsb + zlsb)
		z *= self._regB_schaal
		
		yx = math.atan2(y,x)
		yx = yx + 2*math.pi if yx < 0 else yx
		
		zx = math.atan2(z,x)
		zx = zx + 2*math.pi if zx < 0 else zx
		
		zy = math.atan2(z,y)
		zy = zy + 2*math.pi if zy < 0 else zy
		
		return (yx, zx, zy)
		

#=== FUN
compass = HMC5883L()

try:
	while True:
		
		hoek = math.degrees(compass.meet()[0])
		print(hoek)		
		time.sleep(1)

except KeyboardInterrupt:
	pass
